config/routes.rb
Rails.application.routes.draw do
  root "static_pages_controller#home" 
  get "/about", to: "static_pages_controller#about"
  resources :people
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/person.rb
class Person < ApplicationRecord

  def self.name_order
    order(:first_name)
  end

  def full_name
    "#{self.first_name} #{self.last_name}"
  end

  def alive_or
    if self.alive == true
       "#{self.first_name} is still alive"
    else 
      "#{self.first_name} is dead"
    end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
    # @people = Person.order(:first_name)
    @people = Person.name_order
  end

  def show
    @person = Person.find(params[:id])
  end

  def new
    @person = Person.new
  end

  def edit 
    @person = Person.find(params[:id])
  end

  def create
    @person = Person.new(person_params)
    if @person.save
      redirect_to people_path
    else
      render :new
    end
  end

  def update
    @person = Person.find(params[:id])
    if @person.update(person_params)
      redirect_to people_path
    else 
      render :new
    end
  end

  def destroy
    @person = Person.find(params[:id]).destroy
    redirect_to people_path
  end

  private
  def person_params
    params.require(:person).permit(:first_name, :last_name, :age, :gender, :hair_color, :eye_color, :alive)
  end
end

app/controllers/static_pages_controller_controller.rb
class StaticPagesControllerController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_navbar.html.erb
<%= link_to "Home", root_path%>
<%= link_to "About", about_path%>
<%= link_to "People", people_path%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PeopleApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
     <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css"
    />

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <nav class= "navbar">
    <%= render 'layouts/navbar' %>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/people/edit.html.erb
<h1>Edit Info</h1>


<%= form_for @person do |f|%>
<%= f.label :first_name %>
<%= f.text_field :first_name %>

<%= f.label :last_name%>
<%= f.text_field :last_name%>

<%= f.label :age%>
<%= f.text_field :age%>

<%= f.label :hair_color%>
<%= f.text_field :hair_color%>

<%= f.label :eye_color%>
<%= f.text_field :eye_color%>

<%= f.label :gender%>
<%= f.text_field :gender%>
<div>
<%= f.label :alive%>
<%= f.check_box :alive%>
</div>
<%= f.submit%>
<% end %>

app/views/people/index.html.erb
<h1 class= "header">People People</h1>
<button class="button"><%= link_to "New", new_person_path%></button>
<hr />
<div class= container>
<% @people.each do |person|%>

<div class = person-container>
<div class = person-info>
<h2><%= person.full_name %></h2>
<p><%= person.alive_or%></p>
</div>
<div class= "button-div">
<button class="button is-success">
<%= link_to "More", person_path(person.id)%>
</button>

<button class="button is-warning">
<%= link_to "Edit", edit_person_path(person.id)%>
</button>

<button class= "button is-danger">
<%= link_to "Delete", person_path(person), method: :delete%>
</button>
  </div>
</div>
<%end%>
</div>

app/views/people/new.html.erb
<h1>People#new</h1>
<p>Find me in app/views/people/new.html.erb</p>

app/views/people/show.html.erb
<h1><%= @person.full_name%></h1>
<h3>Age: <%= @person.age%></h3>
<h3>Hair Color: <%= @person.hair_color%></h3>
<h3>Eye Color: <%= @person.eye_color%></h3>
<h3>Gender: <%= @person.gender%></h3>
<h3><%= @person.alive_or%></h3>

app/views/static_pages_controller/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages_controller/home.html.erb
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>